# Generated by Django 5.1.7 on 2025-03-24 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDKActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdk', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(199999999999)])),
                ('cdk', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='commodityinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('num', models.IntegerField()),
                ('details', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='topupinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptoday', models.IntegerField()),
                ('uptotal', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo', to_field='account')),
            ],
        ),
        migrations.CreateModel(
            name='sinkingorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('ordernumber', models.TextField(max_length=100)),
                ('state', models.BooleanField(default=False)),
                ('commodity', models.TextField(max_length=100)),
                ('zfbordernumber', models.TextField(default='0', max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo', to_field='account')),
            ],
        ),
    ]
