# Generated by Django 5.1.7 on 2025-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinfo',
            name='commodity_image',
            field=models.ImageField(default=123, upload_to='commodity_images'),
            preserve_default=False,
        ),
    ]
