# Generated by Django 5.1.7 on 2025-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_commodityinfo_commodity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfo',
            name='commodity_image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='商品图片'),
        ),
    ]
