# Generated by Django 5.1.7 on 2025-03-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_commodityinfo_commodity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkingorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sinkingorder',
            name='commodity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sinkingorder',
            name='ordernumber',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='sinkingorder',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sinkingorder',
            name='zfbordernumber',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
