# Generated by Django 5.1.7 on 2025-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_sinkingorder_price_alter_sinkingorder_commodity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinkingorder',
            name='state',
        ),
        migrations.AddField(
            model_name='sinkingorder',
            name='error_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sinkingorder',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已完成'), (3, '失败')], default=0),
        ),
        migrations.AddField(
            model_name='sinkingorder',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
