# Generated by Django 5.1.7 on 2025-03-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_sinkingorder_state_sinkingorder_error_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinkingorder',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
