"""
Django settings for gamemall project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import redis

# from celery_config.backends import redis
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yirxcef0ty07it_@ri3fn@cp7f=*-*$3u3#4a7-_+g&8=w8z*k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 关闭调试模式
# if DEBUG:
#     STATICFILES_DIRS = [
#         os.path.join(BASE_DIR, "userapp/static"),
#     ]
# else:
#     STATICFILES_DIRS = []  # 生产环境无需指定
ALLOWED_HOSTS = ['127.0.0.1', 'localhost','*']  # 允许所有主机访问，或替换为服务器IP


LANGUAGE_CODE = 'zh-hans'  # 使用中文（简体）

# USE_I18N = True  # 启用国际化
# USE_L10N = True  # 启用本地化

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userapp.apps.UserappConfig',
    'pay.apps.PayConfig',
    'admin_panel.apps.AdminPanelConfig',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gamemall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gamemall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gamemall',
        'USER': 'root',
        'PASSWORD': 'cnm471787',
        'HOST': 'mysql8',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 30,  # 连接超时时间
        },
        'CONN_MAX_AGE': 300,  # 连接保持时间（秒）
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



BASE_DIR = Path(__file__).resolve().parent.parent
# settings.py
# 静态文件 URL 路径（浏览器访问时使用的路径）
STATIC_URL = '/static/'

# 静态文件收集目录（必须与 Docker 挂载路径一致）
#STATIC_ROOT = '/app/static'  # 容器内路径
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 静态文件源目录（从这些目录收集文件）
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfile'),  # 包含 userapp 的静态文件         # 根目录下的静态文件（如果有）
]


# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# 添加CELERY配置
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXPIRES = 3600  # 1小时过期

# Celery监控配置
CELERY_BROKER_HOST = 'redis'  # Docker容器名称
CELERY_BROKER_PORT = 6379
CELERY_BROKER_DB = 0
CELERY_BROKER_PASSWORD = ''  # 如果有密码需要设置
CELERY_DEFAULT_QUEUE = 'celery'  # 默认队列名称



# 外部API配置
EXTERNAL_API_URL = 'http://159.75.94.194:84/ht1/vip/api.php'
EXTERNAL_API_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 QuarkPC/2.3.5.270'
EXTERNAL_API_COOKIE = 'b39a87411be1e3a83e8b30607842a26c_ssl=9c940c48-9b23-40eb-95bb-5395a7a98e6b.ttC_dvOAQFENek8hdpWx8wQvbRQ'
EXTERNAL_API_REFERER = 'http://159.75.94.194:84/ht1/vip/'
API_SECRET_KEY = 'cnm123'  # 建议改为从环境变量读取



# 连接池配置（可选优化项）
CELERY_BROKER_POOL = redis.ConnectionPool(
    host='redis',
    port=6379,
    db=0,
    max_connections=20
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 支付宝沙箱配置
# 支付宝配置（直接读取密钥内容，避免路径拼接）
ALIPAY_APP_ID = '2021000147643342'
ALIPAY_PRIVATE_KEY = Path(BASE_DIR / 'pay' / 'keys' / 'app_private_key.pem').read_text()
ALIPAY_PUBLIC_KEY = Path(BASE_DIR / 'pay' / 'keys' / 'alipay_public_key.pem').read_text()
ALIPAY_RETURN_URL = 'http://47.117.188.91/alipay/return/'
ALIPAY_NOTIFY_URL = 'http://47.117.188.91/alipay/notify/'
ALIPAY_DEBUG = True
ALIPAY_GATEWAY = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'
